#ifndef CONSTANTS_H_INCLUDED
#define CONSTANTS_H_INCLUDED

#define MAX_PROJECTILES 100
#define MAX_METEORS 100
#define SCREEN_WIDTH 512
#define SCREEN_HEIGHT 700
#define GAME_TITLE "Space Ascend"

#endif // CONSTANTS_H_INCLUDED
